name: Build and Deploy to FTP

on:
  push:
    branches:
      - main # Change this to master if that is your primary branch

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 🔧 Use Node.js
      uses: actions/setup-node@v4
      with:
        node-size: 20
        cache: 'npm'

    - name: 📦 Install dependencies
      run: npm ci

    - name: 🏗️ Build Project
      run: npm run build

    - name: 🚀 Sync Files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # The local folder containing built production assets
        local-dir: ./dist/
        # The destination directory on your FTP server (defaults to root if omitted)
        server-dir: ${{ secrets.FTP_REMOTE_PATH }}
        # Setting to true helps avoid payload issues on some FTP servers
        state-name: .ftp-deploy-sync-state.json
